image: php:7.2

stage:
    - lint
    - deploy
    
linter:
    stage: lint
    image: pipelinecomponents/php-codesniffer:latest
    script:
        - php phpcs.phar --extentions=php --standard=PSR2
    tags:
        - lint

deployToAWS:
    only:
        - master
    stage: deploy
    script:
        - bash deploy/deploy.sh