image: php:7.2

stages:
    - lint
    - deploy
    
linter:
    stage: lint
    image: pipelinecomponents/php-codesniffer:latest
    script:
        - php phpcbf.phar --extensions=php --standard=PSR2

# deployToAWS:
#     only:
#         - master
#     stage: deploy
#     script:
#         - bash deploy/deploy.sh