image: php:7.2

stage:
    - lint
    
linter:
    stage: lint
    image: pipelinecomponents/php-codesniffer:latest
    script:
        - php phpcs.phar --extions=php --standard=PSR2
    tags:
        - lint